import 'package:dio/dio.dart';
import 'package:get/get.dart' hide Response, FormData, MultipartFile;
import 'package:pro_23/constant/api_constant.dart';
import 'package:pro_23/core/util/api_client.dart';

import '../core/util/api_exception.dart';
import '../model/post/post_data_model.dart';
import '../service/storage_service.dart';

class PostRepository {
  PostRepository(this._api);
  final Dio dio = Dio();
  final StorageService storage = Get.find<StorageService>();

  final ApiClient _api;

  Future<(PostDataModel?, String?)> getPageTest({int page = 0, int size = 10, String? title, bool? published,}) async {
    try {
      final response = await _api.get(
        ApiConstant.posts,
        query: {
          'page': page,
          'size': size,
          'sortBy': 'createdAt',
          'direction': 'desc',
          if (title != null && title.isNotEmpty) 'title': title,
          if (published != null) 'published': published,
        },
      );

      print('Repository');
      print(response);

      return (PostDataModel.fromJson(response), null);
    } catch (e) {
      return (null, e.toString());
    }
  }

  Future<(Data?, String?)> createPost({required String title, required String content, required bool published}) async {
    try {
      final response = await _api.post(
        ApiConstant.posts,
        body: {
          'title': title,
          'content': content,
          'published': published,
        },
      );
      print('========== CREATE USER RESPONSE ==========');
      print('RESPONSE: $response');
      print('==========================================');
      // 2. ApiClient only returns here if status code is 2xx.
      // Extract the 'data' map from the response JSON body.
      final dynamic dataJson = response['data'];

      if (dataJson != null) {
        // 3. Return the parsed userData model
        return (Data.fromJson(dataJson), null);
      }

      return (null, 'Unexpected response format from server');
    } on ApiException catch (e) {
      // Catch the custom exception generated by ApiClient
      print('Create user API error: ${e.message}');
      return (null, e.message);
    } catch (e) {
      // Catch any other unexpected mapping or local errors
      print('Create user unexpected error: $e');
      return (null, e.toString());
    }
  }

  Future<(bool, String?)> uploadPostImage({required int postId, required String filePath}) async {
    try {

      await _api.upload(
          ApiConstant.postImage(postId),
          filePath: filePath
      );
      return (true, null);
    } on DioException catch (e) {
      return (
      false,
      e.response?.data?['message']?.toString() ??
          e.message ??
          'Image upload failed',
      );
    } catch (e) {
      print(e);
      return (false, e.toString());
    }
  }

  // =========================
// Update Post
// =========================

  Future<(Data?, String?)> updatePost({required int id, required String title, required String content, required bool published,}) async {
    try {
      final responses = await _api.put(
          ApiConstant.postById(id),
          body: {
            'title': title,
            'content': content,
            'published': published
          }
      );

      final data = responses['data'];

      if (data == null){
        return (null, 'No post data returned');
      }

      final post = Data.fromJson(
        Map<String, dynamic>.from(data),
      );

      return (post, null);
    } on ApiException catch (e) {
      // Catch the custom exception generated by ApiClient
      print('Update user API error: ${e.message}');
      return (null, e.message);
    } catch (e) {
      // Catch any other unexpected mapping or local errors
      print('Update user unexpected error: $e');
      return (null, e.toString());
    }
  }

  // =========================
// Delete Post
// =========================

  Future<(bool, String?)> deletePost({required int id}) async {
    try {
      await _api.delete(ApiConstant.postById(id));
      return (true, null);
    } on ApiException catch (e) {
      // Catch the custom exception generated by ApiClient
      print('Create user API error: ${e.message}');
      return (false, e.message);
    } catch (e) {
      // Catch any other unexpected mapping or local errors
      print('Create user unexpected error: $e');
      return (false, e.toString());
    }
  }
}
